md_app/events/forms.py
from flask_wtf import FlaskForm
from wtforms import SelectField, SubmitField, StringField, TextAreaField
from wtforms.fields.html5 import DateField
from wtforms.validators import DataRequired


class EventForm(FlaskForm):
    startDate = DateField('Start date', validators=[DataRequired()])
    endDate = DateField("End date (if ongoing, select today's date and update later)", validators=[DataRequired()])
    pain = SelectField('Pain level', choices=[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10], coerce=int)
    nv = SelectField('Nausea &/or vomiting', choices=['Neither', 'Felt nauseous and/or was sick'])
    phonophoto = SelectField('Aversion to light &/or sounds', choices=['Neither', 'Unable to tolerate bright lights/loud sounds'])
    adls = SelectField('Effect on normal activities', choices=['Able to continue', 'Not able to continue'])
    period = SelectField('Relation to menstrual cycle', choices=['Not within -2 to +3 days of start of menstruation', 'Within -2 to +3 days of start of menstruation'])
    acutetx1 = SelectField('Select any acute treatment taken',
                           choices=['None', 'Aspirin 300mg', 'Aspirin 600mg', 'Aspirin 900mg', 'Ibuprofen 400mg', 'Ibuprofen 600mg', 'Paracetamol 500mg', 'Paracetamol 1000mg',
                                    'Diclofenac 25mg', 'Naproxen 250mg', 'Metoclopromide 10mg', 'Domperidone 10mg', 'Prochlorperazine 10mg', 'Sumatriptan 50mg tablet',
                                    'Sumatriptan 100mg tablet', 'Sumatriptan 10mg nasal spray', 'Sumatriptan 20mg nasal spray', 'Almotriptan 12.5mg', 'Eletriptan 40mg',
                                    'Frovatriptan 2.5mg', 'Naratriptan 2.5mg', 'Rizatriptan 10mg', 'Zolmitriptan 5mg', 'Other'])
    acutetx2 = SelectField('Select any acute treatment taken',
                           choices=['None', 'Aspirin 300mg', 'Aspirin 600mg', 'Aspirin 900mg', 'Ibuprofen 400mg', 'Ibuprofen 600mg', 'Paracetamol 500mg', 'Paracetamol 1000mg',
                                    'Diclofenac 25mg', 'Naproxen 250mg', 'Metoclopromide 10mg', 'Domperidone 10mg', 'Prochlorperazine 10mg', 'Sumatriptan 50mg tablet',
                                    'Sumatriptan 100mg tablet', 'Sumatriptan 10mg nasal spray', 'Sumatriptan 20mg nasal spray', 'Almotriptan 12.5mg', 'Eletriptan 40mg',
                                    'Frovatriptan 2.5mg', 'Naratriptan 2.5mg', 'Rizatriptan 10mg', 'Zolmitriptan 5mg', 'Other'])
    acutetx3 = SelectField('Select any acute treatment taken',
                           choices=['None', 'Aspirin 300mg', 'Aspirin 600mg', 'Aspirin 900mg', 'Ibuprofen 400mg', 'Ibuprofen 600mg', 'Paracetamol 500mg', 'Paracetamol 1000mg',
                                    'Diclofenac 25mg', 'Naproxen 250mg', 'Metoclopromide 10mg', 'Domperidone 10mg', 'Prochlorperazine 10mg', 'Sumatriptan 50mg tablet',
                                    'Sumatriptan 100mg tablet', 'Sumatriptan 10mg nasal spray', 'Sumatriptan 20mg nasal spray', 'Almotriptan 12.5mg', 'Eletriptan 40mg',
                                    'Frovatriptan 2.5mg', 'Naratriptan 2.5mg', 'Rizatriptan 10mg', 'Zolmitriptan 5mg', 'Other'])
    acutetxSuccess = SelectField('Was pain improved 2 hours after taking treatment?', choices=['None taken', 'No', 'Slightly', 'Greatly', 'Completely resolved headache'])
    prophylactic = SelectField('Are you currently taking a preventative?', choices=['No', 'Amitriptyline', 'Candesartan', 'Propanolol', 'Topiramate', 'Erenumab (Aimovig)', 'Fremanezumab (Ajovy)', 'Galcanezumab (Emgality)'])
    prophylacticDose = StringField('Enter total daily dose of preventative medication currently taken')
    triggers = SelectField('Any potential triggers for this attack?', choices=['None', 'Irregular sleep', 'Altered meal times', 'Dietary changes', 'Increased exercise', 'Decreased exercise', 'Stress'])
    notes = TextAreaField('Any further notes?')
    submit = SubmitField('Save Headache Event')

md_app/events/routes.py
from flask import Blueprint, render_template, url_for, flash, redirect, request, abort
from md_app import db
from md_app.models import HeadacheEvent
from md_app.events.forms import EventForm
from flask_login import current_user, login_required


events = Blueprint('events', __name__)


@events.route("/event/new", methods=['GET', 'POST'])
@login_required
def new_event():
    form = EventForm()
    if form.validate_on_submit():
        event = HeadacheEvent(
                    startDate=form.startDate.data,
                    endDate=form.endDate.data,
                    pain=form.pain.data,
                    nv=form.nv.data,
                    phonophoto=form.phonophoto.data,
                    adls=form.adls.data,
                    period=form.period.data,
                    acutetx1=form.acutetx1.data,
                    acutetx2=form.acutetx2.data,
                    acutetx3=form.acutetx3.data,
                    acutetxSuccess=form.acutetxSuccess.data,
                    prophylactic=form.prophylactic.data,
                    prophylacticDose=form.prophylacticDose.data,
                    triggers=form.triggers.data,
                    notes=form.notes.data,
                    migraineur=current_user
                    )
        db.session.add(event)
        db.session.commit()
        flash('Event has been saved', 'success')
        return redirect(url_for('events.headache_diary'))
    return render_template('create_event.html', title='New Event', form=form, legend='Add Headache event')


@events.route("/headachediary", methods=['GET', 'POST'])
@login_required
def headache_diary():
    page = request.args.get('page', 1, type=int)
    events = HeadacheEvent.query.filter_by(user_id=current_user.id).order_by(HeadacheEvent.startDate.desc()).paginate(page=page, per_page=10)
    return render_template('headachediary.html', events=events)


@events.route("/event/<int:event_id>")
@login_required
def event(event_id):
    event = HeadacheEvent.query.get_or_404(event_id)
    if event.migraineur != current_user:
        abort(403)
    return render_template('event.html', title=event.startDate.strftime('%d/%m/%Y'), event=event)


@events.route("/event/<int:event_id>/update", methods=['GET', 'POST'])
@login_required
def update_event(event_id):
    event = HeadacheEvent.query.get_or_404(event_id)
    if event.migraineur != current_user:
        abort(403)
    form = EventForm()
    if form.validate_on_submit():
        event.startDate = form.startDate.data
        event.endDate = form.endDate.data
        event.pain = form.pain.data
        event.nv = form.nv.data
        event.phonophoto = form.phonophoto.data
        event.adls = form.adls.data
        event.period = form.period.data
        event.acutetx1 = form.acutetx1.data
        event.acutetx2 = form.acutetx2.data
        event.acutetx3 = form.acutetx3.data
        event.acutetxSuccess = form.acutetxSuccess.data
        event.prophylactic = form.prophylactic.data
        event.prophylacticDose = form.prophylacticDose.data
        event.triggers = form.triggers.data
        event.notes = form.notes.data
        db.session.commit()
        flash('Event has been updated', 'success')
        return redirect(url_for('events.event', event_id=event.id))
    elif request.method == 'GET':
        form.startDate.data = event.startDate
        form.endDate.data = event.endDate
        form.pain.data = event.pain
        form.nv.data = event.nv
        form.phonophoto.data = event.phonophoto
        form.adls.data = event.adls
        form.period.data = event.period
        form.acutetx1.data = event.acutetx1
        form.acutetx2.data = event.acutetx2
        form.acutetx3.data = event.acutetx3
        form.acutetxSuccess.data = event.acutetxSuccess
        form.prophylactic.data = event.prophylactic
        form.prophylacticDose.data = event.prophylacticDose
        form.triggers.data = event.triggers
        form.notes.data = event.notes
    return render_template('create_event.html', title='Update Event', form=form, legend='Update headache event')


@events.route("/event/<int:event_id>/delete", methods=['POST'])
@login_required
def delete_event(event_id):
    event = HeadacheEvent.query.get_or_404(event_id)
    if event.migraineur != current_user:
        abort(403)
    db.session.delete(event)
    db.session.commit()
    flash('Event has been deleted', 'success')
    return redirect(url_for('events.headache_diary'))


@events.route("/headachediary/summary", methods=['GET', 'POST'])
@login_required
def diary_summary():
    events = HeadacheEvent.query.filter_by(user_id=current_user.id).all()
    return render_template('diarysummary.html', events=events)

md_app/main/routes.py
from flask import Blueprint, render_template

main = Blueprint('main', __name__)


@main.route("/")
@main.route("/home")
def home():
    return render_template('home.html')


@main.route("/about")
def about():
    return render_template('about.html')

md_app/users/routes.py
from flask import Blueprint, render_template, url_for, flash, redirect, request
from md_app import bcrypt, db
from md_app.models import User
from md_app.users.forms import RegistrationForm, LoginForm, UpdateAccountForm, RequestResetForm, PasswordResetForm
from flask_login import login_user, current_user, logout_user, login_required
from md_app.users.utils import send_reset_email

users = Blueprint('users', __name__)


@ users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash('Your account has been created! You are now able to log in', 'success')
        logout_user()
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)


@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login unsuccessful. Please check email and password', 'danger')
    return render_template('login.html', title='Login', form=form)


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home'))


@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your account info has been updated!', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    return render_template('account.html', title='Account', form=form)


@users.route("/reset_password", methods=['GET', 'POST'])
def request_reset():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with instructions to reset your password', 'info')
        return redirect(url_for('users.login'))
    return render_template('request_reset.html', title='Reset Password', form=form)


@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def password_reset(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('Password reset request is invalid or has expired', 'warning')
        return redirect(url_for('users.request_reset'))
    form = PasswordResetForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Your password has been changed. You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('password_reset.html', title='Password reset', form=form)

md_app/templates/about.html
{% extends "layout.html" %}
{% block content %}
  <h1>About Page</h1>
{% endblock content %}

md_app/templates/account.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
          <div class="media">
                <div class="media-body">
                      <h2 class="account-heading">{{ current_user.email }}</h>
                          <p class="text-secondary">{{ current_user.username }}</p>
                          <p class="text-secondary">GP/practice name</p>
                </div>
          </div>
              <form method="POST" action="">
                  {{ form.hidden_tag() }}
                  <fieldset class="form-group">
                      <legend class="border-bottom mb-4">Update account info</legend>
                      <div class="form-group">
                          {{ form.username.label(class="form-control-label") }}

                          {% if form.username.errors %}
                              {{ form.username(class="form-control form-control-lg is-invalid") }}
                              <div class="invalid-feedback">
                                  {% for error in form.username.errors %}
                                      <span>{{ error }}</span>
                                  {% endfor %}
                              </div>
                          {% else %}
                              {{ form.username(class="form-control form-control-lg") }}
                          {% endif %}
                      </div>
                      <div class="form-group">
                          {{ form.email.label(class="form-control-label") }}
                          {% if form.email.errors %}
                              {{ form.email(class="form-control form-control-lg is-invalid") }}
                              <div class="invalid-feedback">
                                  {% for error in form.email.errors %}
                                      <span>{{ error }}</span>
                                  {% endfor %}
                              </div>
                          {% else %}
                              {{ form.email(class="form-control form-control-lg") }}
                          {% endif %}
                      </div>
                    </fieldset>
                  <div class="form-group">
                      {{ form.submit(class="btn btn-outline-info") }}
                  </div>
              </form>
    </div>
{% endblock content %}

md_app/templates/diarysummary.html
{% extends "layout.html" %}
{% block content %}
<h1>Headache diary summary</h1>
    <article class="media content-section">
        <div class="media-body">
            <div class="article-metadata">
                <p>Total headache days:</p>
                <p>Monthly headache days:<p>
                <p>Total migraine days:<p>
                <p>Monthly migraine days:<p>
                <p>If >=4 migraine days/month, offer preventative</p>
                <p>Month-by-month trend in headache and migraine days</p>
            </div>
            <div class="article-metadata">
                <p></p>
                <h5>Summary of analgesic use</h5>
                <p></p>
                <p>Simple analgesia:</p>
                <p>Triptan:</p>
                <p></p>
                <p>Month-by-month trend of acute treatment usage</p>
                <h6>Overall risk of MOH</p>
            </div>
            </div>
            </div>
        </div>
    </article>
{% endblock content %}

md_app/templates/event.html
{% extends "layout.html" %}
{% block content %}
<h1>Headache event</h1>
    <article class="media content-section">
        <div class="media-body">
            <div class="article-metadata">
                {% if event.startDate == event.endDate %}
                    <h5 class="article-title">{{ event.startDate.strftime('%d/%m/%Y') }}</h5>
                {% else %}
                    <h5 class="article-title"> {{ event.startDate.strftime('%d/%m/%Y') }} - {{ event.endDate.strftime('%d/%m/%Y') }}</h5>
                {% endif %}
        </div>
            <div class="article-metadata">
            <p class="article-content"> Pain: {{ event.pain }}</p>
            <p class="article-content"> Nausea/vomiting: {{ event.nv }}</p>
            <p class="article-content"> Aversion to light/sound: {{ event.phonophoto }}</p>
            <p class="article-content"> Ability to continue regular activities: {{ event.adls }}</p>
            <p class="article-content"> Relation to menstrual cycle: {{ event.period }}</p>
            <p class="article-content"> Treatment(s) taken:{% if event.acutetx1 == 'None' and event.acutetx2 == 'None' and event.acutetx3 == 'None' %} None {% endif %}{% if event.acutetx1 != 'None' %} {{ event.acutetx1 }} {% endif %}{% if event.acutetx2 != 'None' %} {{ event.acutetx2 }} {% endif %}{% if event.acutetx3 != 'None' %} {{ event.acutetx3 }} {% endif %}</p>
            <p class="article-content"> Did treatment help? {{ event.acutetxSuccess }}</p>
            <p class="article-content"> Preventative medication: {{ event.prophylactic }} {{ event.prophylacticDose }}</p>
            <p class="article-content"> Potential triggers: {{ event.triggers }}</p>
            <p class="article-content"> Notes: {{ event.notes }}</p>
            </div>
            <div>
                 <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('events.update_event', event_id=event.id) }}">
                     Update
                 </a>
                  <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">
                      Delete
                  </button>
            </div>
        </div>
    </article>
<!-- Modal -->
     <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
       <div class="modal-dialog" role="document">
         <div class="modal-content">
           <div class="modal-header">
             <h5 class="modal-title" id="deleteModalLabel">Delete Post?</h5>
             <button type="button" class="close" data-dismiss="modal" aria-label="Close">
               <span aria-hidden="true">&times;</span>
             </button>
           </div>
           <div class="modal-footer">
             <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
             <form action="{{ url_for('events.delete_event', event_id=event.id) }}" method="POST">
               <input class="btn btn-danger" type="submit" value="Delete">
             </form>
           </div>
         </div>
       </div>
     </div>
{% endblock content %}

md_app/templates/headachediary.html
{% extends "layout.html" %}
{% block content %}
<h1>My Headache Diary</h1>
    {% for event in events.items %}
        <article class="media content-section">
              <div class="media-body">
                    <div class="article-metadata">
                          <h5><a class="article-title" href="{{ url_for('events.event', event_id=event.id) }}">{{ event.startDate.strftime('%d/%m/%Y') }}</a></h5>
                    </div>
              </div>
        </article>
    {% endfor %}
    {% for page_num in events.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
        {% if page_num %}
            {% if events.page == page_num %}
                <a class="btn btn-info mb-4" href="{{ url_for('events.headache_diary', page=page_num) }}">{{ page_num }}</a>
            {% else %}
                <a class="btn btn-outline-info mb-4" href="{{ url_for('events.headache_diary', page=page_num) }}">{{ page_num }}</a>
            {% endif %}
        {% else %}
        ...
        {% endif %}
    {% endfor %}
{% endblock content %}

md_app/templates/home.html
{% extends "layout.html" %}
{% block content %}
    <h1>Home Page</h1>
{% endblock content %}

md_app/templates/layout.html
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <style>
    body {
      background: #fafafa;
      color: #333333;
      margin-top: 5rem;
    }

    h1, h2, h3, h4, h5, h6 {
      color: #444444;
    }

    .bg-steel {
      background-color: #a58fcf;
    }

    .site-header .navbar-nav .nav-link {
      color: #ffffff;
    }

    .site-header .navbar-nav .nav-link:hover {
      color: #f7da65;
    }

    .site-header .navbar-nav .nav-link.active {
      font-weight: 500;
    }

    .content-section {
      background: #ffffff;
      padding: 10px 20px;
      border: 1px solid #dddddd;
      border-radius: 3px;
      margin-bottom: 20px;
    }

    .article-title {
      color: #444444;
    }

    a.article-title:hover {
      color: #428bca;
      text-decoration: none;
    }

    .article-content {
      white-space: pre-line;
    }

    .article-img {
      height: 65px;
      width: 65px;
      margin-right: 16px;
    }

    .article-metadata {
      padding-bottom: 1px;
      margin-bottom: 4px;
      border-bottom: 1px solid #e3e3e3
    }

    .article-metadata a:hover {
      color: #333;
      text-decoration: none;
    }

    .article-svg {
      width: 25px;
      height: 25px;
      vertical-align: middle;
    }

    .account-img {
      height: 125px;
      width: 125px;
      margin-right: 20px;
      margin-bottom: 16px;
    }

    .account-heading {
      font-size: 2.5rem;
    }
    </style>

    {% if title %}
        <title>MigraDoc - {{ title }}</title>
    {% else %}
        <title>MigraDoc</title>
    {% endif %}
</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="/">MigraDoc</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
            {% if current_user.is_authenticated %}
                <a class="nav-item nav-link" href="#">Personal care plan</a>
                <a class="nav-item nav-link" href="{{ url_for ('events.headache_diary') }}">Headache Diary</a>
                <a class="nav-item nav-link" href="{{ url_for('events.diary_summary') }}">Diary summary</a>
                <a class="nav-item nav-link" href="{{ url_for ('events.new_event') }}">Add Headache event</a>
                <a class="nav-item nav-link" href="#">Resources</a>
             {% else %}
                <a class="nav-item nav-link" href="{{ url_for('main.about') }}">About</a>
                <a class="nav-item nav-link" href="#">Resources</a>
            {% endif %}
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
                {% if current_user.is_authenticated %}
                    <a class="nav-item nav-link" href="{{ url_for('users.account') }}">Account</a>
                    <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>
                {% else %}
                    <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
                    <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
                {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
          {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
              {% for category, message in messages %}
                <div class="alert alert-{{ category }}">
                  {{ message }}
                </div>
              {% endfor %}
            {% endif %}
          {% endwith %}
          {% block content %}{% endblock %}
        </div>
        <div class="col-md-4">
          <div class="content-section">
            <h3>Resources</h3>
            <p class='text-muted'>You can put any information here you'd like.
              <ul class="list-group">
                <li class="list-group-item list-group-item-light">Red flags</li>
                <li class="list-group-item list-group-item-light">Diagnosis summary</li>
                <li class="list-group-item list-group-item-light">Prophylactic treatment protocols</li>
                <li class="list-group-item list-group-item-light">Other primary headache disorders</li>
                <li class="list-group-item list-group-item-light">When to refer</li>
                <li class="list-group-item list-group-item-light">Template letter of diagnosis for employer (pg 10 toolkit)</li>
                <li class="list-group-item list-group-item-light">Different resources for patients e.g.</li>
                <li class="list-group-item list-group-item-light">What is migraine, common triggers, MOH, premonitory sx/postdrome</li>
                <li class="list-group-item list-group-item-light">Signpost Migraine Trust</li>
                <li class="list-group-item list-group-item-light">Advice for employment</li>
              </ul>
            </p>
          </div>
        </div>
      </div>
    </main>


    <!-- Optional JavaScript -->
    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
</body>
</html>

md_app/templates/login.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log In</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-check">
                    {{ form.remember(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-label") }}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
            <small class="text-muted ml-2">
                <a href="{{ url_for('users.request_reset') }}">Forgot Password?</a>
            </small>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Need An Account? <a class="ml-2" href="{{ url_for('users.register') }}">Sign Up Now</a>
        </small>
    </div>
{% endblock content %}

md_app/templates/password_reset.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Reset Password</legend>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.confirm_password.label(class="form-control-label") }}
                    {% if form.confirm_password.errors %}
                        {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.confirm_password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.confirm_password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
    <div class="border-top pt-3">
    </div>
{% endblock content %}